import streamlit as st

st.title("CONCRETE SURROUND CREATE FROM SELECTED PIPE")

st.video(r"pics/Workflow/CONCRETE_SURROUND_CREATE_FROM_SELECTED_PIPE/CONCRETE_SURROUND_CREATE_FROM_SELECTED_PIPE.mp4",autoplay=True)

